#!/usr/bin/env python3
"""
Backtest engine for the Crypto Analysis AI algorithm.
Fetches real historical ETH/USDT daily data from Binance and simulates
trading signals generated by the analysis.ts logic.
"""

import json
import math
import urllib.request
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import List, Optional, Dict

# ─── CONFIG ─────────────────────────────────────────────────────────────────
SYMBOL = "ETHUSDT"
INTERVAL = "1d"
START_DATE = "2024-06-13"
END_DATE = "2025-06-13"
INITIAL_CAPITAL = 10_000.0           # USD
POSITION_SIZE_PCT = 0.95             # % of capital per trade
STOP_LOSS_PCT = 0.07                 # 7% stop loss
TAKE_PROFIT_SHORT_PCT = 0.12         # 12% TP for short-term trades
FEE_PCT = 0.001                      # 0.1% per trade (Binance spot)

# ─── DATA STRUCTURES ────────────────────────────────────────────────────────

@dataclass
class Candle:
    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: float

@dataclass
class TechnicalIndicators:
    rsi: int
    macd: str
    ma50: float
    ma200: float
    support_levels: List[float]
    resistance_levels: List[float]
    trend: str

@dataclass
class SentimentData:
    fear_greed_index: int
    fear_greed_label: str
    social_sentiment: str

@dataclass
class OnChainData:
    funding_rate: float
    exchange_net_flow: str

@dataclass
class OrderBookData:
    bid_ask_ratio: float

@dataclass
class WhaleData:
    accumulation: str

@dataclass
class TimeframeData:
    dominant_trend: str
    alignment: str

@dataclass
class ElliottWaveData:
    trend: str
    current_wave: int

@dataclass
class SmcData:
    market_structure: str
    last_bos: Optional[str]
    structure_shift: bool

@dataclass
class AnalysisResult:
    price: float
    change_24h: float
    technical: TechnicalIndicators
    sentiment: SentimentData
    on_chain: OnChainData
    order_book: OrderBookData
    whale: WhaleData
    timeframe: TimeframeData
    elliott_wave: ElliottWaveData
    smc: SmcData
    verdict_short_term: str
    verdict_long_term: str
    confidence: float
    stop_loss: float
    take_profit_short: float
    take_profit_long: float

@dataclass
class Trade:
    entry_date: str
    entry_price: float
    direction: str       # 'long' or 'short'
    size_usd: float
    exit_price: Optional[float] = None
    exit_date: Optional[str] = None
    pnl: float = 0.0
    exit_reason: str = ""

@dataclass
class BacktestState:
    cash: float
    position: Optional[Dict] = None   # None = flat
    trades: List[Trade] = field(default_factory=list)
    equity_curve: List[float] = field(default_factory=list)
    dates: List[str] = field(default_factory=list)

# ─── BINANCE DATA FETCHER ───────────────────────────────────────────────────

def fetch_binance_klines(symbol: str, interval: str, start_ms: int, end_ms: int) -> List[Candle]:
    """Fetch historical candle data from Binance public API."""
    url = (f"https://api.binance.com/api/v3/klines"
           f"?symbol={symbol}&interval={interval}"
           f"&startTime={start_ms}&endTime={end_ms}&limit=1000")
    
    with urllib.request.urlopen(url, timeout=30) as response:
        data = json.loads(response.read().decode())
    
    candles = []
    for k in data:
        candles.append(Candle(
            timestamp=int(k[0]),
            open=float(k[1]),
            high=float(k[2]),
            low=float(k[3]),
            close=float(k[4]),
            volume=float(k[5])
        ))
    return candles

# ─── ANALYSIS LOGIC (Ported from analysis.ts) ──────────────────────────────

def calculate_ema(prices: List[float], period: int) -> List[float]:
    """Calculate Exponential Moving Average."""
    if len(prices) < period:
        return [sum(prices) / len(prices)] if prices else []
    
    multiplier = 2.0 / (period + 1)
    ema = [sum(prices[:period]) / period]
    
    for price in prices[period:]:
        ema.append((price - ema[-1]) * multiplier + ema[-1])
    
    # Pad with first EMA value
    return [ema[0]] * (period - 1) + ema

def calculate_rsi(closes: List[float], period: int = 14) -> List[float]:
    """Calculate RSI for a list of closing prices."""
    if len(closes) < period + 1:
        return [50.0] * len(closes)
    
    rsis = [50.0] * period  # Neutral RSI for first 'period' candles
    
    for i in range(period, len(closes)):
        gains = []
        losses = []
        for j in range(i - period + 1, i + 1):
            change = closes[j] - closes[j - 1]
            if change > 0:
                gains.append(change)
            else:
                losses.append(abs(change))
        
        avg_gain = sum(gains) / period if gains else 0
        avg_loss = sum(losses) / period if losses else 0
        
        if avg_loss == 0:
            rsis.append(100.0)
        else:
            rs = avg_gain / avg_loss
            rsis.append(100.0 - (100.0 / (1 + rs)))
    
    return rsis

def calculate_ma(prices: List[float], period: int) -> List[float]:
    """Calculate Simple Moving Average."""
    if len(prices) < period:
        return [sum(prices) / len(prices)] if prices else []
    
    mas = []
    for i in range(len(prices)):
        if i < period - 1:
            mas.append(sum(prices[:i+1]) / (i + 1))
        else:
            mas.append(sum(prices[i - period + 1:i + 1]) / period)
    return mas

def round_price(value: float) -> float:
    if abs(value) < 10:
        return round(value, 4)
    return round(value)

def parse_technical_indicators(price: float, change_24h: float, closes: List[float]) -> TechnicalIndicators:
    rsi = round(50 + (change_24h > 0 and change_24h * 1.5 or change_24h * 1.5) * -1)
    clamped_rsi = max(15, min(85, rsi))
    
    # Calculate actual MAs from historical data
    ma50_vals = calculate_ma(closes, 50)
    ma200_vals = calculate_ma(closes, 200)
    ma50 = ma50_vals[-1] if ma50_vals else price * (0.97 if change_24h > 0 else 1.03)
    ma200 = ma200_vals[-1] if ma200_vals else price * (0.92 if change_24h > 0 else 1.08)
    
    return TechnicalIndicators(
        rsi=clamped_rsi,
        macd="bearish crossover" if clamped_rsi < 40 else "bullish crossover" if clamped_rsi > 60 else "neutral",
        ma50=ma50,
        ma200=ma200,
        support_levels=[
            round_price(price * 0.95),
            round_price(price * 0.90),
            round_price(price * 0.85)
        ],
        resistance_levels=[
            round_price(price * 1.04),
            round_price(price * 1.08),
            round_price(price * 1.15)
        ],
        trend="bullish" if change_24h > 2 else "bearish" if change_24h < -2 else "neutral"
    )

def parse_sentiment_data(fear_greed_idx: int) -> SentimentData:
    return SentimentData(
        fear_greed_index=fear_greed_idx,
        fear_greed_label="Fear" if fear_greed_idx < 25 else "Greed" if fear_greed_idx > 75 else "Neutral",
        social_sentiment="bearish" if fear_greed_idx < 30 else "bullish" if fear_greed_idx > 70 else "neutral"
    )

def parse_elliott_wave_data(price: float, change_24h: float, trend: str) -> ElliottWaveData:
    is_bullish = change_24h > 0
    abs_change = abs(change_24h)
    
    if abs_change < 1:
        return ElliottWaveData(trend="neutral", current_wave=0)
    elif is_bullish and abs_change > 4:
        return ElliottWaveData(trend="impulse", current_wave=3)
    elif is_bullish:
        return ElliottWaveData(trend="impulse", current_wave=1)
    elif abs_change > 4:
        return ElliottWaveData(trend="corrective", current_wave=-3)
    else:
        return ElliottWaveData(trend="corrective", current_wave=-1)

def parse_smc_data(price: float, change_24h: float, elliott_wave: ElliottWaveData) -> SmcData:
    is_bullish = change_24h > 0
    is_ranging = abs(change_24h) < 1
    
    return SmcData(
        market_structure="uptrend" if is_bullish and not is_ranging else "downtrend" if not is_bullish and not is_ranging else "ranging",
        last_bos="bullish" if is_bullish and abs(change_24h) > 3 else "bearish" if not is_bullish and abs(change_24h) > 3 else None,
        structure_shift=abs(change_24h) > 3 and ((is_bullish and elliott_wave.trend == "bearish") or (not is_bullish and elliott_wave.trend == "bullish"))
    )

def build_verdict(
    price: float,
    technical: TechnicalIndicators,
    on_chain: OnChainData,
    sentiment: SentimentData,
    order_book: OrderBookData,
    whale: WhaleData,
    timeframe: TimeframeData,
    elliott_wave: ElliottWaveData,
    smc: SmcData
):
    """Ported from buildVerdict in analysis.ts."""
    bearish_score = (
        (technical.trend == "bearish" and 3 or 0) +
        (technical.rsi > 70 and 2 or technical.rsi < 30 and -1 or 0) +
        (on_chain.funding_rate > 0.005 and 3 or 0) +
        (sentiment.fear_greed_index < 25 and 2 or 0) +
        (order_book.bid_ask_ratio < 0.9 and 2 or 0) +
        (whale.accumulation == "distributing" and 2 or 0) +
        (timeframe.dominant_trend == "bearish" and 3 or timeframe.dominant_trend == "bullish" and -1 or 0) +
        (timeframe.alignment == "aligned" and timeframe.dominant_trend == "bearish" and 3 or 0) +
        (elliott_wave.trend == "impulse" and elliott_wave.current_wave >= 5 and 3 or 0) +
        (elliott_wave.current_wave <= -3 and 2 or 0) +
        (smc.market_structure == "downtrend" and 2 or 0) +
        (smc.last_bos == "bearish" and 2 or 0)
    )

    bullish_score = (
        (technical.trend == "bullish" and 3 or 0) +
        (technical.rsi < 30 and 2 or technical.rsi > 70 and -1 or 0) +
        (on_chain.funding_rate < 0.001 and 2 or 0) +
        (sentiment.fear_greed_index > 70 and 2 or 0) +
        (order_book.bid_ask_ratio > 1.1 and 2 or 0) +
        (whale.accumulation == "accumulating" and 2 or 0) +
        (timeframe.dominant_trend == "bullish" and 3 or timeframe.dominant_trend == "bearish" and -1 or 0) +
        (timeframe.alignment == "aligned" and timeframe.dominant_trend == "bullish" and 3 or 0) +
        (elliott_wave.trend == "impulse" and elliott_wave.current_wave <= 3 and 3 or 0) +
        (elliott_wave.current_wave <= -2 and -2 or 0) +
        (smc.market_structure == "uptrend" and 2 or 0) +
        (smc.last_bos == "bullish" and 2 or 0) +
        (smc.structure_shift and 3 or 0)
    )

    net_score = bullish_score - bearish_score

    if sentiment.fear_greed_index < 20:
        if net_score >= 4:
            net_score = max(net_score - 2, 1)
        else:
            net_score -= 1

    short_term = "hold"
    long_term = "hold"
    confidence = 50
    stop_loss = round_price(price * 0.93)
    take_profit_short = round_price(price * 1.12)
    take_profit_long = round_price(price * 1.35)

    if net_score >= 4:
        short_term = "buy"
        long_term = "buy"
        confidence = min(85, 50 + net_score * 8)
        stop_loss = round_price(price * 0.93)
        take_profit_short = round_price(price * 1.12)
        take_profit_long = round_price(price * 1.35)
    elif net_score >= 1:
        short_term = "hold"
        long_term = "buy"
        confidence = min(70, 40 + net_score * 8)
        stop_loss = round_price(price * 0.92)
        take_profit_short = round_price(price * 1.08)
        take_profit_long = round_price(price * 1.25)
    elif net_score >= -2:
        short_term = "hold"
        long_term = "hold"
        confidence = min(60, 40 + abs(net_score) * 5)
        stop_loss = round_price(price * 0.90)
        take_profit_short = round_price(price * 1.05)
        take_profit_long = round_price(price * 1.15)
    else:
        short_term = "sell"
        long_term = "hold"
        confidence = min(80, 50 + abs(net_score) * 7)
        stop_loss = round_price(price * 1.05)
        take_profit_short = round_price(price * 0.95)
        take_profit_long = round_price(price * 1.10)

    return short_term, long_term, confidence, stop_loss, take_profit_short, take_profit_long

def analyze_day(candles: List[Candle], idx: int, fear_greed_idx: int = 50) -> AnalysisResult:
    """Run the analysis logic for a single day."""
    current = candles[idx]
    prev = candles[idx - 1] if idx > 0 else current
    
    price = current.close
    change_24h = ((current.close - prev.close) / prev.close) * 100 if prev.close else 0
    
    closes = [c.close for c in candles[:idx + 1]]
    technical = parse_technical_indicators(price, change_24h, closes)
    
    # Simulate other data points
    sentiment = parse_sentiment_data(fear_greed_idx)
    on_chain = OnChainData(funding_rate=0.005 + (hash(str(idx)) % 1000 / 100000), exchange_net_flow="outflows (-)")
    order_book = OrderBookData(bid_ask_ratio=1.0 + (hash(str(idx)) % 100 / 500))
    whale = WhaleData(accumulation="neutral")
    timeframe = TimeframeData(dominant_trend=technical.trend, alignment="conflicting")
    elliott = parse_elliott_wave_data(price, change_24h, technical.trend)
    smc = parse_smc_data(price, change_24h, elliott)
    
    short, long_v, conf, sl, tp_s, tp_l = build_verdict(
        price, technical, on_chain, sentiment, order_book, whale, timeframe, elliott, smc
    )
    
    return AnalysisResult(
        price=price,
        change_24h=change_24h,
        technical=technical,
        sentiment=sentiment,
        on_chain=on_chain,
        order_book=order_book,
        whale=whale,
        timeframe=timeframe,
        elliott_wave=elliott,
        smc=smc,
        verdict_short_term=short,
        verdict_long_term=long_v,
        confidence=conf,
        stop_loss=sl,
        take_profit_short=tp_s,
        take_profit_long=tp_l
    )

# ─── BACKTEST ENGINE ─────────────────────────────────────────────────────────

def run_backtest(candles: List[Candle]) -> BacktestState:
    """Run the strategy backtest over historical data."""
    state = BacktestState(cash=INITIAL_CAPITAL)
    
    for i in range(1, len(candles)):
        candle = candles[i]
        date_str = datetime.fromtimestamp(candle.timestamp / 1000).strftime("%Y-%m-%d")
        prev_candle = candles[i - 1]
        
        analysis = analyze_day(candles, i)
        
        # ── EXIT LOGIC ──
        if state.position:
            pos = state.position
            days_in_trade = i - pos["entry_idx"]
            
            # Check stop loss
            if pos["direction"] == "long" and candle.low <= pos["stop_loss"]:
                exit_price = pos["stop_loss"]
                pnl = (exit_price - pos["entry_price"]) / pos["entry_price"] * pos["size_usd"]
                state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
                state.trades.append(Trade(
                    entry_date=pos["entry_date"], entry_price=pos["entry_price"],
                    direction="long", size_usd=pos["size_usd"], exit_price=exit_price,
                    exit_date=date_str, pnl=pnl, exit_reason="stop_loss"
                ))
                state.position = None
            
            elif pos["direction"] == "short" and candle.high >= pos["stop_loss"]:
                exit_price = pos["stop_loss"]
                pnl = (pos["entry_price"] - exit_price) / pos["entry_price"] * pos["size_usd"]
                state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
                state.trades.append(Trade(
                    entry_date=pos["entry_date"], entry_price=pos["entry_price"],
                    direction="short", size_usd=pos["size_usd"], exit_price=exit_price,
                    exit_date=date_str, pnl=pnl, exit_reason="stop_loss"
                ))
                state.position = None
            
            # Check take profit (short term)
            elif pos["direction"] == "long" and candle.high >= pos["take_profit"]:
                exit_price = pos["take_profit"]
                pnl = (exit_price - pos["entry_price"]) / pos["entry_price"] * pos["size_usd"]
                state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
                state.trades.append(Trade(
                    entry_date=pos["entry_date"], entry_price=pos["entry_price"],
                    direction="long", size_usd=pos["size_usd"], exit_price=exit_price,
                    exit_date=date_str, pnl=pnl, exit_reason="take_profit"
                ))
                state.position = None
            
            elif pos["direction"] == "short" and candle.low <= pos["take_profit"]:
                exit_price = pos["take_profit"]
                pnl = (pos["entry_price"] - exit_price) / pos["entry_price"] * pos["size_usd"]
                state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
                state.trades.append(Trade(
                    entry_date=pos["entry_date"], entry_price=pos["entry_price"],
                    direction="short", size_usd=pos["size_usd"], exit_price=exit_price,
                    exit_date=date_str, pnl=pnl, exit_reason="take_profit"
                ))
                state.position = None
            
            # Check signal reversal (exit if opposite signal)
            elif (pos["direction"] == "long" and analysis.verdict_short_term == "sell") or \
                 (pos["direction"] == "short" and analysis.verdict_short_term == "buy"):
                exit_price = candle.close
                if pos["direction"] == "long":
                    pnl = (exit_price - pos["entry_price"]) / pos["entry_price"] * pos["size_usd"]
                else:
                    pnl = (pos["entry_price"] - exit_price) / pos["entry_price"] * pos["size_usd"]
                state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
                state.trades.append(Trade(
                    entry_date=pos["entry_date"], entry_price=pos["entry_price"],
                    direction=pos["direction"], size_usd=pos["size_usd"], exit_price=exit_price,
                    exit_date=date_str, pnl=pnl, exit_reason="signal_reversal"
                ))
                state.position = None

        # ── ENTRY LOGIC ──
        if not state.position:
            if analysis.verdict_short_term == "buy":
                size_usd = state.cash * POSITION_SIZE_PCT
                state.cash -= size_usd
                state.position = {
                    "direction": "long",
                    "entry_price": candle.close,
                    "stop_loss": analysis.stop_loss,
                    "take_profit": analysis.take_profit_short,
                    "size_usd": size_usd,
                    "entry_date": date_str,
                    "entry_idx": i
                }
            elif analysis.verdict_short_term == "sell":
                size_usd = state.cash * POSITION_SIZE_PCT
                state.cash -= size_usd
                state.position = {
                    "direction": "short",
                    "entry_price": candle.close,
                    "stop_loss": analysis.stop_loss,
                    "take_profit": analysis.take_profit_short,
                    "size_usd": size_usd,
                    "entry_date": date_str,
                    "entry_idx": i
                }
        
        # Track equity
        equity = state.cash
        if state.position:
            current_value = state.position["size_usd"]
            if state.position["direction"] == "long":
                current_value *= (candle.close / state.position["entry_price"])
            else:
                current_value *= (state.position["entry_price"] / candle.close)
            equity += current_value
        
        state.equity_curve.append(equity)
        state.dates.append(date_str)
    
    # Close any open position at the end
    if state.position:
        pos = state.position
        exit_price = candles[-1].close
        if pos["direction"] == "long":
            pnl = (exit_price - pos["entry_price"]) / pos["entry_price"] * pos["size_usd"]
        else:
            pnl = (pos["entry_price"] - exit_price) / pos["entry_price"] * pos["size_usd"]
        state.cash += pos["size_usd"] + pnl - (pos["size_usd"] * FEE_PCT)
        state.trades.append(Trade(
            entry_date=pos["entry_date"], entry_price=pos["entry_price"],
            direction=pos["direction"], size_usd=pos["size_usd"], exit_price=exit_price,
            exit_date=datetime.fromtimestamp(candles[-1].timestamp / 1000).strftime("%Y-%m-%d"),
            pnl=pnl, exit_reason="end_of_test"
        ))
        state.position = None
    
    return state

# ─── REPORTING ──────────────────────────────────────────────────────────────

def print_report(state: BacktestState):
    """Print backtest summary."""
    print("="*60)
    print(" BACKTEST REPORT")
    print("="*60)
    print(f"\nInitial Capital:    ${INITIAL_CAPITAL:,.2f}")
    print(f"Final Value:        ${state.equity_curve[-1]:,.2f}")
    print(f"Total Return:        {((state.equity_curve[-1] / INITIAL_CAPITAL) - 1) * 100:.2f}%")
    print(f"Number of Trades:    {len(state.trades)}")
    
    winning_trades = [t for t in state.trades if t.pnl > 0]
    losing_trades = [t for t in state.trades if t.pnl <= 0]
    
    print(f"Winning Trades:      {len(winning_trades)}")
    print(f"Losing Trades:       {len(losing_trades)}")
    print(f"Win Rate:            {len(winning_trades) / len(state.trades) * 100:.1f}%" if state.trades else "N/A")
    
    total_pnl = sum(t.pnl for t in state.trades)
    print(f"Total P&L:          ${total_pnl:,.2f}")
    
    avg_win = sum(t.pnl for t in winning_trades) / len(winning_trades) if winning_trades else 0
    avg_loss = sum(t.pnl for t in losing_trades) / len(losing_trades) if losing_trades else 0
    print(f"Avg Win:            ${avg_win:,.2f}")
    print(f"Avg Loss:           ${avg_loss:,.2f}")
    
    # Sharpe ratio (simplified)
    returns = []
    for i in range(1, len(state.equity_curve)):
        if state.equity_curve[i-1] > 0:
            returns.append((state.equity_curve[i] - state.equity_curve[i-1]) / state.equity_curve[i-1])
    
    if returns:
        avg_return = sum(returns) / len(returns)
        std_dev = math.sqrt(sum((r - avg_return)**2 for r in returns) / len(returns))
        sharpe = (avg_return / std_dev) * math.sqrt(365) if std_dev > 0 else 0
        print(f"Sharpe Ratio:        {sharpe:.3f}")
    
    print("\n" + "="*60)
    print("  Recent Trades:")
    print("="*60)
    for t in state.trades[-5:]:
        print(f"  {t.entry_date} | {t.direction.upper():4} | Entry: ${t.entry_price:,.2f} | "
              f"Exit: ${t.exit_price:,.2f} | P&L: ${t.pnl:,.2f} | {t.exit_reason}")

# ─── MAIN ───────────────────────────────────────────────────────────────────

def main():
    print(f"Fetching {SYMBOL} {INTERVAL} data from {START_DATE} to {END_DATE}...")
    start_ms = int(datetime.strptime(START_DATE, "%Y-%m-%d").timestamp()) * 1000
    end_ms = int(datetime.strptime(END_DATE, "%Y-%m-%d").timestamp()) * 1000
    
    candles = fetch_binance_klines(SYMBOL, INTERVAL, start_ms, end_ms)
    print(f"Got {len(candles)} candles")
    
    if len(candles) < 50:
        print("Not enough data for backtest!")
        return
    
    print(f"Running backtest with initial capital ${INITIAL_CAPITAL:,.2f}...")
    state = run_backtest(candles)
    
    print_report(state)
    
    # Save data for charting
    output = {
        "dates": state.dates,
        "equity": state.equity_curve,
        "trades": [
            {
                "entry_date": t.entry_date, "entry_price": t.entry_price,
                "direction": t.direction, "size_usd": t.size_usd,
                "exit_price": t.exit_price, "exit_date": t.exit_date,
                "pnl": t.pnl, "exit_reason": t.exit_reason
            }
            for t in state.trades
        ],
        "candles": [
            {
                "date": datetime.fromtimestamp(c.timestamp / 1000).strftime("%Y-%m-%d"),
                "open": c.open, "high": c.high, "low": c.low, "close": c.close, "volume": c.volume
            }
            for c in candles[1:]
        ]
    }
    with open("backtest_result.json", "w") as f:
        json.dump(output, f, indent=2)
    print("\nData saved to backtest_result.json")

if __name__ == "__main__":
    main()
